---
- name: create-sql-rds
  hosts: localhost
  connection: local
  vars_files: 
    - db-vault.yml 
  gather_facts : false
  roles:
    - sql-rds-install

- name: SQL Server
  hosts: localhost
  vars_files: 
    - db-vault.yml 
  connection: local
  roles:
    - createdb_and_executescript

